name: Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          vercel build --prod --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

      - name: Notify success deployment
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "✅ Deployment for senkou-hero.vercel.app successfully completed!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify failed deployment
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"text": "❌ Deployment for senkou-hero.vercel.app failed!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
